version: '3.0'

services:
  db:
    restart: always
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bookrental
  
  api:
    restart: always
    build: api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_NAME: bookrental
      DB_PASSWORD: pass
      JWT_SECRET: secret
    ports:
      - 3000:3000
    depends_on:
      - db

  web:
    restart: always
    build: web
    ports:
      - 8080:80
