export const Constants = {
  SEQUELIZE: 'SEQUELIZE',
  REPOSITORY: {
    BOOK_GENRE: 'REPOSITORY_BOOK_GENRE',
    BOOK: 'REPOSITORY_BOOK',
    GENRE: 'REPOSITORY_GENRE',
    LANGUAGE: 'REPOSITORY_LANGUAGE',
    RENTAL: 'REPOSITORY_RENTAL',
    USER: 'REPOSITORY_USER',
  },
};
